"""Update Verdict schema to v1

Revision ID: 06a7129eb2cb
Revises: 222aa1c30fd4
Create Date: 2026-08-28 20:25:46.388818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a7129eb2cb'
down_revision: Union[str, Sequence[str], None] = '222aa1c30fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verdicts', sa.Column('schema_version', sa.String(), nullable=False))
    op.add_column('verdicts', sa.Column('validity', sa.Enum('VALID', 'INVALID', name='verdictvalidity'), nullable=False))
    op.add_column('verdicts', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('verdicts', sa.Column('rationale', sa.Text(), nullable=False))
    op.add_column('verdicts', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('verdicts', sa.Column('verification_status', sa.String(), nullable=False))
    op.add_column('verdicts', sa.Column('label_normalization_version', sa.String(), nullable=False))
    op.drop_column('verdicts', 'confidence_score')
    op.drop_column('verdicts', 'explanation')
    op.drop_column('verdicts', 'poc_source_code')
    op.drop_column('verdicts', 'poc_result')
    op.drop_column('verdicts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verdicts', sa.Column('status', sa.VARCHAR(length=10), nullable=False))
    op.add_column('verdicts', sa.Column('poc_result', sa.TEXT(), nullable=True))
    op.add_column('verdicts', sa.Column('poc_source_code', sa.TEXT(), nullable=True))
    op.add_column('verdicts', sa.Column('explanation', sa.TEXT(), nullable=False))
    op.add_column('verdicts', sa.Column('confidence_score', sa.FLOAT(), nullable=False))
    op.drop_column('verdicts', 'label_normalization_version')
    op.drop_column('verdicts', 'verification_status')
    op.drop_column('verdicts', 'evidence')
    op.drop_column('verdicts', 'rationale')
    op.drop_column('verdicts', 'confidence')
    op.drop_column('verdicts', 'validity')
    op.drop_column('verdicts', 'schema_version')
    # ### end Alembic commands ###
